# Generated by Django 6.0.2 on 2026-02-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre de la categoría')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Disponible?')),
                ('nro_orden', models.IntegerField(default=0, verbose_name='Número de orden')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nro_orden', 'nombre', 'disponible'],
            },
        ),
    ]
