# Generated by Django 6.0.2 on 2026-02-11 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['categoria__nombre', 'nombre', 'precio', 'disponible'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.CreateModel(
            name='VarianteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('es_default', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='menu.producto')),
            ],
            options={
                'ordering': ['es_default', 'precio_extra', 'nombre'],
                'unique_together': {('producto', 'nombre')},
            },
        ),
    ]
